version: '3.3'
services:
  application:
    image: naboo:0.1
    container_name: naboo
    env_file: .env.dev
    environment:
      - DATABASE_URL=postgres://postgres:development@postgresql/naboo_dev
    ports:
      - 4000:4000
    depends_on:
      - postgresql
  postgresql:
    image: postgres:12-alpine
    container_name: naboo-postgres
    environment:
      - POSTGRES_DB=naboo_dev
      - POSTGRES_PASSWORD=development
    ports:
      - 5432:5432
    volumes:
      - naboo_psql:/var/lib/postgresql/data
volumes:
  naboo_psql:
