version: '3.9'
services:

  back-end:
    build:
      context: .
      dockerfile: dockerfile.dev
      args:
        - APP_VERSION: 0.3.2
      image: naboo
    env_file:
      - .env.dev
    environment:
      - MIX_ENV=dev
      - DATABASE_URL=postgres://anon:ChangeMe@database/naboo_dev
      - POSTGRES_PORT=ChangeMe
      - POSTGRES_USER=anon
      - POSTGRES_HOST=database
    ports:
      - 4000:4000
    depends_on:
      - database
    networks:
      - internal

  database:
    image: postgres:12-alpine
    container_name: naboo-postgres
    environment:
      - POSTGRES_USER=anon
      - POSTGRES_DB=naboo_dev
      - POSTGRES_PASSWORD=ChangeMe
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - internal

volumes:
  database:

networks:
  internal:

