version: '3.5'
services:

  back-end:
    build:
      context: .
    env_file:
      - .env.dev
    environment:
      - DATABASE_URL=postgres://anon:ChangeMe@database/naboo
      - POSTGRES_PORT=ChangeMe
      - POSTGRES_USER=anon
      - POSTGRES_HOST=database
    ports:
      - 4000:4000
    depends_on:
      - database
    networks:
      - internal

  database:
    image: postgres:12-alpine
    container_name: naboo-postgres
    environment:
      - POSTGRES_USER=anon
      - POSTGRES_DB=naboo
      - POSTGRES_PASSWORD=ChangeMe
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - internal



volumes:
  database:

networks:
  internal:

