version: '3'
services:
  db:
    image: postgres:14
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - ./:/db/
#  app:
#    build: .
#    env_file: .env
#    ports:
#      - "4000:4000"
#    depends_on:
#      - db
#    volumes:
#      - ./:/app/
