name: CI
on: push
env:
  UT_CI: true
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: 18.7
      - run: npm install nodemon
      - name: launch backend
        run: docker-compose up --exit-code-from app
      - name: check exit code
        if: steps.script.outputs.exitCode
        run: echo "Exit code ${{ steps.script.outputs.exitCode }}"
