name: CI
on: push

env:
  UT_CI: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
 
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v2
      	with:
	  node-version: 18.7
	  
      - name: launch backend
        run: docker-compose up