name: Docker

on:
  push:
    branches:
      - "canon"
    workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v2
        with:
          node-version: 14.18

      - name: Start containers
        run: docker-compose -f "docker-compose.yml" up -d --build

      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down

      - run: npm install

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.LOGIN_DOCKERHUB_TEST }}
          password: ${{ secrets.PASSWORD_DOCKERHUB_TEST }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: bogdzn/naboo

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            APP_VERSION=0.3.2
